### ISSUE TITLE
Ajaran kesatu untuk kontributor baru

### ISSUE THREAD

**Issue by 3442853561** [casaliuqi-com/pydol#5]
Dear contributors, this project uses Indonesian as the working language. However, if you cannot use this language, please use English as an alternative.

Silakan buat ubahan untuk workflow
(Please change the workflow)

```
runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
```
